### ISSUE TITLE
Name of variables in ATL06

### ISSUE THREAD

**Issue by facusapienza21** [ICESAT-2HackWeek/CloudMask#4]
The name of some features in the [ATL06 dictionary](https://nsidc.org/sites/nsidc.org/files/technical-references/ICESat2_ATL06_data_dict_v003.pdf) have been changed in order to have a more descriptive name or sometimes a shorter name. This is in `utils_atl06.py`. For example: 

<img width="662" alt="Screen Shot 2020-09-29 at 10 07 39 PM" src="https://user-images.githubusercontent.com/39526081/94632128-31e44b00-02a0-11eb-9468-722c121e1dc1.png">

Should the names of the variables in the dataframes coincide with the ones in the ATL06 data dictonary?

**Comment by espg** [comment]
@facusapienza21 This is tough question... ideally, we'd be able to do both, i.e., keep the data dictionary names, and also rename things to be sensible. Is it possible to encode the variables in a dictionary, and keep access for both? i.e.,
```
d = { 'lat' : 'latitude', 'lon' : 'longitude', 'height' : 'h_li', 'slope_dx' : dh_fit_dx', ... }
```
The idea being that you can access with `data.height`, but can also access separately with `data.d['h_li']` or something similar?
